version: '3.3'
services:
  ldes-client:
    env_file:
      - ./config.local.env
    container_name: ldes-client
    image: ldes-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    networks:
      - ldes

networks:
  ldes:
    driver: bridge
    